apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80  # Port inside the container

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx  # This selects the Nginx pod by label
  ports:
    - protocol: TCP
      port: 80         # Port exposed inside the cluster
      targetPort: 80    # Port on the container
      nodePort: 30001   # External port to expose via NodePort
  type: NodePort

